version: 2
updates:
  # Enable version updates for npm in the root directory
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    groups:
      next:
        patterns:
          - "next"
          - "@next/third-parties"
          - "eslint-config-next"
      hey-api:
        patterns:
          - "@hey-api*"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/client"
          - "@prisma/adapter-pg"
          - "@types/pg"
          - "pg"
          - "pg-pool"
      radix:
        patterns:
          - "@radix-ui/**"
      tailwind:
        patterns:
          - "tailwind-merge"
          - "tailwindcss-animate"
          - "tw-animate-css"
          - "prettier-plugin-tailwindcss"
          - "@tailwindcss/postcss"
      better-auth:
        patterns:
          - "better-auth"
          - "better-auth-harmony"
          - "@better-auth/utils"
      eslint:
        patterns:
          - "eslint*"
      react:
        patterns:
          - "react"
          - "react-dom"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@sparticuz/chromium"
      - dependency-name: "puppeteer-core"
