version: 2
updates:
  # Enable version updates for npm in the root directory
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mrgrauel"
      - "bytegen-dev"
      - "golddydev"
    commit-message:
      prefix: "build(deps)"

  # Enable version updates for npm in the web-app directory
  - package-ecosystem: "npm"
    directory: "/web-app"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mrgrauel"
      - "bytegen-dev"
      - "golddydev"
    commit-message:
      prefix: "build(deps)"
  
  # Enable version updates for npm in the job-cron-caller directory
  - package-ecosystem: "npm"
    directory: "/job-cron-caller"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mrgrauel"
      - "bytegen-dev"
      - "golddydev"
    commit-message:
      prefix: "build(deps)"
  
  # Enable version updates for npm in the registry-cron-caller directory
  - package-ecosystem: "npm"
    directory: "/registry-cron-caller"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mrgrauel"
      - "bytegen-dev"
      - "golddydev"
    commit-message:
      prefix: "build(deps)"