name: Build Sync Function

on:
  workflow_dispatch:
  pull_request:
    paths: ['sync-function/**']

env:
  ADMIN_KEY: ${{ vars.PUBLIC_DEFAULT_SECRET }}
  SOKOSUMI_API_URL: ${{ vars.PUBLIC_DEFAULT_URL }}

jobs:
  build-sync-function:
    name: Build Sync Function
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sync-function
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm i

      - name: Lint
        run: pnpm run lint

      - name: Run Build
        run: pnpm run build
