name: Release Sync Function Deployment

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  deploy-function:
    name: Deploy Function
    runs-on: ubuntu-latest
    environment: production
    env:
      SOKOSUMI_URL: ${{ vars.SOKOSUMI_URL }}
      ADMIN_KEY: ${{ secrets.ADMIN_KEY }}
      SOKOSUMI_FUNCTION_NAMESPACE: ${{ vars.SOKOSUMI_FUNCTION_NAMESPACE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm masumi-sync:build

      - name: Install serverless
        run: pnpm masumi-sync:doctl:install

      - name: Configure serverless connect
        run: pnpm masumi-sync:doctl:connect
        env:
          namespace: ${{ vars.SOKOSUMI_FUNCTION_NAMESPACE }}

      - name: Deploy
        run: pnpm masumi-sync:doctl:deploy
