name: Release Deployment

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  deploy-web-app:
    name: Deploy Web App
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy the app
        uses: digitalocean/app_action/deploy@v2
        env:
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          RESEND_FROM_EMAIL: ${{ vars.RESEND_FROM_EMAIL }}
          BETTER_AUTH_URL: ${{ vars.BETTER_AUTH_URL }}
          GOOGLE_CLIENT_ID: ${{ vars.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          MICROSOFT_CLIENT_ID: ${{ vars.MICROSOFT_CLIENT_ID }}
          MICROSOFT_CLIENT_SECRET: ${{ secrets.MICROSOFT_CLIENT_SECRET }}
          APPLE_CLIENT_ID: ${{ vars.APPLE_CLIENT_ID }}
          APPLE_CLIENT_SECRET: ${{ secrets.APPLE_CLIENT_SECRET }}
          ADMIN_KEY: ${{ secrets.ADMIN_KEY }}
          NEXT_PUBLIC_NETWORK: ${{ vars.NEXT_PUBLIC_NETWORK }}
          REGISTRY_API_KEY: ${{ secrets.REGISTRY_API_KEY }}
          PAYMENT_API_KEY: ${{ secrets.PAYMENT_API_KEY }}
          REGISTRY_API_URL: ${{ vars.REGISTRY_API_URL }}
          PAYMENT_API_URL: ${{ vars.PAYMENT_API_URL }}
        with:
          app_name: ${{ vars.DIGITALOCEAN_APP_NAME }}
          project_id: ${{ secrets.DIGITALOCEAN_PROJECT_ID }}
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

  deploy-job-sync-function:
    name: Deploy Job Sync Function
    runs-on: ubuntu-latest
    needs: [deploy-web-app]
    environment: production
    env:
      SOKOSUMI_API_URL: ${{ vars.SOKOSUMI_API_URL }}
      ADMIN_KEY: ${{ secrets.ADMIN_KEY }}
      SOKOSUMI_FUNCTION_NAMESPACE: ${{ vars.SOKOSUMI_FUNCTION_NAMESPACE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: install dependencies
        run: cd job-cron-caller && npm i
      - name: build
        run: cd job-cron-caller && npm run build
      - name: Install serverless
        run: doctl serverless install
      - name: Configure serverless connect
        run: doctl serverless connect ${{ env.SOKOSUMI_FUNCTION_NAMESPACE }}
      - name: deploy
        run: cd job-cron-caller && npm run deploy

  deploy-registry-sync-function:
    name: Deploy Registry Sync Function
    needs: [deploy-job-sync-function]
    runs-on: ubuntu-latest
    environment: production
    env:
      SOKOSUMI_API_URL: ${{ vars.SOKOSUMI_API_URL }}
      ADMIN_KEY: ${{ secrets.ADMIN_KEY }}
      SOKOSUMI_FUNCTION_NAMESPACE: ${{ vars.SOKOSUMI_FUNCTION_NAMESPACE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: install dependencies
        run: cd registry-cron-caller && npm i
      - name: build
        run: cd registry-cron-caller && npm run build
      - name: Install serverless
        run: doctl serverless install
      - name: Configure serverless connect
        run: doctl serverless connect ${{ env.SOKOSUMI_FUNCTION_NAMESPACE }}
      - name: deploy
        run: cd registry-cron-caller && npm run deploy
