name: Test Web App

on:
  workflow_dispatch:
  pull_request:
    paths: ['web-app/**']

env:
  DATABASE_URL: "postgresql://user:password@localhost:5432/sokosumi"
  BETTER_AUTH_SECRET: ${{ vars.PUBLIC_DEFAULT_SECRET }}
  RESEND_API_KEY: ${{ vars.PUBLIC_DEFAULT_SECRET }}
  RESEND_FROM_EMAIL: ${{ vars.PUBLIC_DEFAULT_EMAIL }}
  GOOGLE_CLIENT_ID: ${{ vars.PUBLIC_DEFAULT_SECRET }}
  GOOGLE_CLIENT_SECRET: ${{ vars.PUBLIC_DEFAULT_SECRET }}
  MICROSOFT_CLIENT_ID: ${{ vars.PUBLIC_DEFAULT_SECRET }}
  MICROSOFT_CLIENT_SECRET: ${{ vars.PUBLIC_DEFAULT_SECRET }}
  LINKEDIN_CLIENT_ID: ${{ vars.PUBLIC_DEFAULT_SECRET }}
  LINKEDIN_CLIENT_SECRET: ${{ vars.PUBLIC_DEFAULT_SECRET }}
  APPLE_CLIENT_ID: ${{ vars.PUBLIC_DEFAULT_SECRET }}
  APPLE_CLIENT_SECRET: ${{ vars.PUBLIC_DEFAULT_SECRET }}
  NEXT_PUBLIC_NETWORK: "Preprod"
  ADMIN_KEY: ${{ vars.PUBLIC_DEFAULT_SECRET }}
  PAYMENT_API_KEY: ${{ vars.PUBLIC_DEFAULT_SECRET }}
  REGISTRY_API_KEY: ${{ vars.PUBLIC_DEFAULT_SECRET }}

jobs:
  build-web-app:
    name: Build and Test Web App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-app
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: sokosumi
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "web-app/package-lock.json"

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test:ci

      - name: Run Prisma Migrate
        run: npm run prisma:migrate

      - name: Run Prisma Seed
        run: npm run prisma:seed

      - name: Run Build
        run: npm run build